metadata.format.version = "1.1"

[versions]

# CompileOnly dependencies
velocity = "3.2.0-SNAPSHOT"
# Included in Velocity but not exposed in API
caffeine = "3.1.7"

# Gradle Plugins
blossom = "1.3.1"
shadow = "8.1.1"
runvelocity = "2.1.0"

# Utility Libraries
configurate = "4.1.2"
libby = "1.2.0"

# Dependencies
netty = "4.1.90.Final"

[libraries]
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }

configurate_gson = { group = "org.spongepowered", name = "configurate-gson", version.ref = "configurate" }
libby = { group = "com.github.AlessioDP.libby", name = "libby-velocity", version.ref = "libby" }

netty = { group = "io.netty", name = "netty-all", version.ref = "netty" }

[plugins]
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
runvelocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runvelocity" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
